# Stage 1 — build the app
FROM node:22-alpine AS builder
WORKDIR /usr/src/app

# Install deps (use package-lock for reproducible builds if istnieje)
COPY package*.json ./
RUN npm ci

# Copy sources and run production build
COPY . .
# <- używa konfiguracji production; to tworzy katalog dist/...
RUN npm run build -- --configuration production

# Stage 2 — nginx static server
FROM nginx:stable-alpine
# optional: remove default config
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Replace <DIST_FOLDER> with rzeczywistą nazwą folderu w dist (zobacz angular.json -> outputPath)
# np. jeśli angular.json mówi "outputPath": "dist/inz-app" to użyj dist/inz-app
COPY --from=builder /usr/src/app/dist/semanticui-angular-project /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]